### ISSUE TITLE
ATH black crosses are no longer drawn for previous cycles.

### ISSUE THREAD

**Issue by aidancurry** [giocaizzi/btc-cycles#26]
ATH black crosses are no longer drawn for previous cycles.

**Comment by giocaizzi** [comment]
`cryptocompare` API returns a price for BTC before 2010-7-17 equals 65k, so all ATHs below this get shadowed by this weird price data.

Fixed this in #27, that will be deployed on pip as v0.3.4, setting the start date as 2010-7-17

thanks for opening the issue @aidancurry
