### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by alexk111** [giocaizzi/btc-cycles#5]
Nice chart! Please consider also generating a dark version. Will be useful for cases when the chart is embedded into dark themed environments.

Example:
![Bitcoin Now](https://github.com/giocaizzi/btc-cycles/assets/4675984/d616d439-ee02-4aff-92f9-b2b6fa212f17)

**Comment by giocaizzi** [comment]
I will try to add this in the next release!

**Comment by alexk111** [comment]
Thank you!

**Comment by giocaizzi** [comment]
@alexk111 I implemented themes (dark,light) and customization of colors of single elements.
These changes will be soon out with the new release, that will also implement other data sources for Bitcoin prices.

**Comment by alexk111** [comment]
Awesome, thanks!
